### ISSUE TITLE
Runtime error in  Safari 8 and IE 10

### ISSUE THREAD

**Issue by peterdivvito** [facebook/regenerator#315]
I am using babel and webpack to transpile my app using the babel-preset-env plugin. At some time in the past month the version of regenerator-runtime that was being included changed from 0.10.0 to 0.11.0 and that has caused my app to stop working on IOS Safari 8. The error thrown is

```
TypeError: No default value
  at ? (~/babel-runtime/~/regenerator-runtime/runtime.js:229:0)
```

I then tested it on IE 10 and got a different error but on the same line:

```
null: String expected
  at ? (~/babel-runtime/~/regenerator-runtime/runtime.js:229:0)
```

Forcing regenerator-runtime back to 0.10.0 fixes the issue.

**Comment by benjamn** [comment]
cc @hzoo could this be related to the removal of `babel-plugin-transform-runtime` (#310)?

**Comment by hzoo** [comment]
yes it won't polyfill symbol, promise, etc

**Comment by benjamn** [comment]
@peterdivvito Any chance you could put together a small reproduction? Happy to debug this if it's reproducible.

**Comment by DemonCloud** [comment]
F*CK!!  this runtime lib use symbol lib  breaking change . with babel runtime
